apiVersion: v1
kind: Service
metadata:
  name: dora-exporter
  namespace: dora
  labels:
    app: dora-exporter
spec:
  selector:
    app: dora-exporter
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
