apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: devboard

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: devboard-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_DB: "{{ .dbname }}"
        POSTGRES_URL: "postgres://{{ .username }}:{{ .password }}@postgres:5432/{{ .dbname }}?sslmode=disable"

  dataFrom:
    - extract:
        key: devboard/postgres
