apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: devboard-gateway
  namespace: devboard

spec:
  gatewayClassName: envoy

  # Use our custom EnvoyProxy configuration for THIS Gateway.
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: devboard-proxy

  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same

  - name: https
    port: 443
    protocol: HTTPS
    hostname: devboard.stackforges.com
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: devboard-tls

    allowedRoutes:
      namespaces:
        from: Same


  # Grafana HTTPS listener.
  #
  # Why:
  # The existing HTTPS listener is specifically for
  # devboard.stackforges.com.
  #
  # Grafana uses a different hostname and therefore
  # needs a listener for grafana.stackforges.com.

  - name: grafana-https
    port: 443
    protocol: HTTPS
    hostname: grafana.stackforges.com

    tls:
      mode: Terminate
      certificateRefs:
        - group: ""
          kind: Secret
          name: grafana-tls

    # HTTPRoutes must be in the same namespace as
    # this Gateway.
    allowedRoutes:
      namespaces:
        from: Same

  - name: argocd-https
    port: 443
    protocol: HTTPS
    hostname: argocd.stackforges.com

    tls:
      mode: Terminate
      certificateRefs:
        - group: ""
          kind: Secret
          name: argocd-tls

    # HTTPRoutes must be in the same namespace as
    # this Gateway.
    allowedRoutes:
      namespaces:
        from: Same      