name: deploy container

on:
  workflow_dispatch:
  push:
    branches:
      - feat/github_actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        

      - name: deploy to ec2
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: '${{ secrets.EC2_HOST }}'
          username: '${{ secrets.EC2_USER }}'
          key: '${{ secrets.EC2_SSH_KEY }}'
          script: >
            docker pull
            ${{secrets.DOCKERHUB_USERNAME}}/devboard-fe-master:latest

            docker stop devboard-fe-master || true

            docker rm devboard-fe-master || true

            docker run -d --name devboard-fe-master -p 80:80
            ${{secrets.DOCKERHUB_USERNAME}}/devboard-fe-master:latest
